---

- name: Update apt
  become_user: root
  apt:
    update_cache: yes

- name: Install deps
  become_user: root
  apt:
    name: '{{ item }}'
    state: installed
  with_items:
    - build-essential
    - dos2unix
    - git

- name: Create Directory for Nodejs GPG Key
  file:
    path: /home/vagrant/.tmp
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes